Add optional mapping quality concordance feature to CompareSAMs
broadinstitute/picard pull request #1617
Opened 2020-12-02 14:02 UTC by michaelgatzen

- If the argument OUTPUT_MQ_CONCORDANCE is provided, CompareSAMs will produce a histogram that reflects concordance of mapping qualities between two alignment files.
- Added separate tests for all CompareSAM test cases to check the mapping quality concordance.

----

### Checklist (never delete this)

Never delete this, it is our record that procedure was followed. If you find that for whatever reason one of the checklist points doesn't apply to your PR, you can leave it unchecked but please add an explanation below.

#### Content
- [ ] Added or modified tests to cover changes and any new functionality
- [ ] Edited the README / documentation (if applicable)
- [ ] All tests passing on Travis

#### Review
- [ ] Final thumbs-up from reviewer
- [ ] Rebase, squash and reword as applicable

For more detailed guidelines, see https://github.com/broadinstitute/picard/wiki/Guidelines-for-pull-requests

2021-01-20 18:48 UTC, gbggrant reviewed
Looks good.  Awaiting @kachulis 's input as he was requested for review

2021-01-20 18:48 UTC, gbggrant commented on src/main/java/picard/sam/CompareSAMs.java
> +                comparison.writeMQConcordanceReport(samComparisonArgumentCollection.OUTPUT_MQ_CONCORDANCE, getDefaultHeaders());
Might want to add a:
        IOUtil.assertFileIsWritable(samComparisonArgumentCollection.OUTPUT_MQ_CONCORDANCE);
before the call to generate the concordance report (in order to fail fast if there's a problem writing the file).

2021-01-20 18:48 UTC, gbggrant commented on src/test/java/picard/sam/CompareSAMsTest.java
> +        final Path tmpMQConcordanceOutput = Files.createTempFile("compareSam.mqconcordance", ".tsv");
Please deleteOnExit() any temp files created by the test.

2021-01-20 18:49 UTC, gbggrant approved these changes

2021-01-21 19:51 UTC, kachulis requested changes
Sorry for the long delay on the review @michaelgatzen!   Generally seems good, just a few easy adjustments.

2021-01-21 19:51 UTC, kachulis commented on src/main/java/picard/sam/util/SamComparison.java
> +    public void writeMQConcordanceReport(final File output, final List<Header> headers) {
does this histogram really need to be written out to a separate file?  Can't it just be added to the main metrics output?

2021-01-21 19:51 UTC, kachulis commented on src/main/java/picard/sam/util/SamComparison.java
> +            if (samComparisonArgumentCollection.OUTPUT_MQ_CONCORDANCE != null) {
this doesn't need a separate message.  Stating that the alignments cannot be compared (above) covers that the mapping qualities of the alignments aren't being compared.

2021-01-21 19:51 UTC, kachulis commented on src/main/java/picard/sam/util/SamComparison.java
> +        mappingQualityHistogram.increment(new Pair<>(s1.getMappingQuality(), s2.getMappingQuality()).toString());
I don't think creating a pair object and using its toString method is the best way to  generate this string.  Just build the string yourself instead.  You can write a one line method for it for clarity.

2021-01-21 19:51 UTC, kachulis commented on src/main/java/picard/sam/util/SamComparison.java
> +        if (samComparisonArgumentCollection.OUTPUT_MQ_CONCORDANCE != null) {
don't need separate output.

2021-01-21 19:51 UTC, kachulis commented on src/test/java/picard/sam/CompareSAMsTest.java
> +        if (expectedMQConcordance == null) {
the tool shouldn't throw exception in this case, but in future you can replace this pattern with `Assert.assertThrows`

2021-01-21 19:51 UTC, kachulis commented on src/main/java/picard/sam/util/SamComparison.java
> +                throw new PicardException("Cannot generate mapping quality concordance histogram because the two files cannot be compared (see reason above).");
don't throw an exception.  we want the tool to run successfully and return that the SAM files are different in this case.

2021-01-25 15:17 UTC, merged